# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-09 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('security_quiz', '0003_auto_20180408_0314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'quizzes'},
        ),
        migrations.RemoveField(
            model_name='record',
            name='answer_given',
        ),
        migrations.RemoveField(
            model_name='record',
            name='question',
        ),
        migrations.AddField(
            model_name='record',
            name='quiz_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
